up : 
	sudo docker-compose up -d
	sudo docker exec -it travel-api /bin/bash
	sudo docker ps 

down:
	sudo docker-compose down
	sudo docker rmi app_app
	sudo docker images

restart:
	sudo docker-compose restart
	clear